"""2 attrs removed for formula fixing

Revision ID: cacb5d112a1e
Revises: 1af074cedf5a
Create Date: 2024-04-01 02:49:03.935139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cacb5d112a1e'
down_revision: Union[str, None] = '1af074cedf5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('booking', 'room_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('booking', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('booking', 'total_days')
    op.drop_column('booking', 'total_cost')
    op.alter_column('room', 'hotel_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('room', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('room', 'services',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('room', 'services',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('room', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('room', 'hotel_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('booking', sa.Column('total_cost', sa.INTEGER(), sa.Computed('(price * (date_from - date_to))', persisted=True), autoincrement=False, nullable=True))
    op.add_column('booking', sa.Column('total_days', sa.INTEGER(), sa.Computed('(date_from - date_to)', persisted=True), autoincrement=False, nullable=True))
    op.alter_column('booking', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('booking', 'room_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
