"""2 attrs fixed

Revision ID: d65822419f95
Revises: cacb5d112a1e
Create Date: 2024-04-01 02:50:03.721637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd65822419f95'
down_revision: Union[str, None] = 'cacb5d112a1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('total_cost', sa.Integer(), sa.Computed('price * (date_to - date_from)', ), nullable=True))
    op.add_column('booking', sa.Column('total_days', sa.Integer(), sa.Computed('(date_to - date_from)', ), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking', 'total_days')
    op.drop_column('booking', 'total_cost')
    # ### end Alembic commands ###
